CREATE TABLE IF NOT EXISTS `purchase_replenishment_analysis` (
  `analysis_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '采购补货分析ID',
  `analysis_no` VARCHAR(50) NOT NULL COMMENT '采购补货分析编号',
  `selected_period_days` INT NOT NULL COMMENT '选择周期天数',
  `item_count` INT NOT NULL DEFAULT 0 COMMENT '分析商品数',
  `total_formula_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '公式建议总量',
  `total_recommended_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '最终建议总量',
  `analysis_status` VARCHAR(30) NOT NULL DEFAULT 'analyzed' COMMENT '分析状态',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `analysis_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '分析时间',
  PRIMARY KEY (`analysis_id`),
  UNIQUE KEY `uk_purchase_replenishment_analysis_no` (`analysis_no`),
  KEY `idx_purchase_replenishment_analysis_time` (`analysis_time`),
  KEY `idx_purchase_replenishment_analysis_status` (`analysis_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='采购智能补货分析主表';

CREATE TABLE IF NOT EXISTS `purchase_replenishment_analysis_item` (
  `item_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '采购补货分析明细ID',
  `analysis_id` BIGINT UNSIGNED NOT NULL COMMENT '采购补货分析ID',
  `warehouse_code` VARCHAR(50) NOT NULL COMMENT '一级库编码',
  `warehouse_name` VARCHAR(80) NOT NULL COMMENT '一级库名称',
  `warehouse_type` VARCHAR(30) DEFAULT NULL COMMENT '库房类型',
  `supplier_name` VARCHAR(120) DEFAULT NULL COMMENT '供应商名称',
  `product_code` VARCHAR(50) NOT NULL COMMENT '商品编码',
  `product_name` VARCHAR(120) NOT NULL COMMENT '商品名称',
  `spec_model` VARCHAR(120) DEFAULT NULL COMMENT '规格型号',
  `unit` VARCHAR(20) DEFAULT NULL COMMENT '单位',
  `purchase_price` DECIMAL(18,4) DEFAULT NULL COMMENT '采购单价',
  `min_purchase_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '最小采购量',
  `current_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '一级库当前可用库存',
  `issue_5_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '5天出库数量',
  `issue_15_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '15天出库数量',
  `issue_30_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '30天出库数量',
  `issue_45_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '45天出库数量',
  `issue_60_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '60天出库数量',
  `selected_issue_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '所选周期出库数量',
  `formula_replenish_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '公式补货数量',
  `recommended_qty` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '最终建议采购数量',
  `manual_adjusted_qty` DECIMAL(18,4) DEFAULT NULL COMMENT '人工调整数量',
  `formula_text` VARCHAR(255) DEFAULT NULL COMMENT '公式说明',
  PRIMARY KEY (`item_id`),
  KEY `idx_purchase_replenishment_item_analysis` (`analysis_id`),
  KEY `idx_purchase_replenishment_item_product` (`product_code`),
  KEY `idx_purchase_replenishment_item_warehouse` (`warehouse_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='采购智能补货分析明细表';
