CREATE TABLE supplier_invoice (
  invoice_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice_no VARCHAR(40) NOT NULL COMMENT 'SPD invoice document number',
  supplier_id BIGINT UNSIGNED NOT NULL,
  invoice_code VARCHAR(40) NOT NULL,
  invoice_number VARCHAR(80) NOT NULL,
  invoice_date DATE NOT NULL,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  settlement_id BIGINT UNSIGNED NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pending_verification',
  remark VARCHAR(500) NULL,
  verify_time DATETIME NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (invoice_id),
  UNIQUE KEY uk_supplier_invoice_no (invoice_no),
  UNIQUE KEY uk_supplier_invoice_identity (supplier_id, invoice_code, invoice_number),
  KEY idx_supplier_invoice_date (invoice_date),
  KEY idx_supplier_invoice_status (status),
  KEY idx_supplier_invoice_settlement (settlement_id),
  CONSTRAINT fk_supplier_invoice_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (supplier_id),
  CONSTRAINT fk_supplier_invoice_settlement FOREIGN KEY (settlement_id) REFERENCES settlement_bill (settlement_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Supplier invoice registration and verification';
