CREATE TABLE IF NOT EXISTS `inventory_daily_summary` (
  `summary_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '日报快照ID',
  `business_date` DATE NOT NULL COMMENT '业务日期',
  `snapshot_time` DATETIME NOT NULL COMMENT '快照生成时点（次日00:00:00）',
  `warehouse_id` BIGINT UNSIGNED NOT NULL COMMENT '库房ID',
  `product_id` BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
  `batch_id` BIGINT UNSIGNED NOT NULL COMMENT '库存批次ID',
  `supplier_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '批次入库配送商ID',
  `opening_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '期初库存',
  `inbound_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '本期入库',
  `return_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '本期退库',
  `requisition_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '本期领用',
  `consumption_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '本期消耗',
  `scrap_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '本期报废',
  `closing_quantity` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '期末库存',
  `unit_price` DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '批次入库单价',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`summary_id`),
  UNIQUE KEY `uk_inventory_daily_summary` (`business_date`, `warehouse_id`, `product_id`, `batch_id`),
  KEY `idx_inventory_daily_summary_date` (`business_date`),
  KEY `idx_inventory_daily_summary_product` (`product_id`, `business_date`),
  KEY `idx_inventory_daily_summary_warehouse` (`warehouse_id`, `business_date`),
  KEY `idx_inventory_daily_summary_supplier` (`supplier_id`, `business_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='全院物资每日进销存快照表';
