CREATE DATABASE IF NOT EXISTS `ISPD`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY 'admin123';
CREATE USER IF NOT EXISTS 'admin'@'127.0.0.1' IDENTIFIED BY 'admin123';

GRANT ALL PRIVILEGES ON `ISPD`.* TO 'admin'@'localhost';
GRANT ALL PRIVILEGES ON `ISPD`.* TO 'admin'@'127.0.0.1';

FLUSH PRIVILEGES;
